title: CADNET Dataset
description: Associated with the paper 'A Convolutional Neural Network Approach to the Classification of Engineering Models'
show_downloads: true
google_analytics: UA-138678802-1
theme: jekyll-theme-dinky
